// Agent labels
def zOsAgentLabel = env.ZOS_AGENT_LABEL ? env.ZOS_AGENT_LABEL : 'e2e-pipeline'
def linuxAgent = 'master'

// Verbose
def verbose = true
//def verbose = false

// Private
def buildVerbose = ''
//def buildVerbose = ''

pipeline {

    agent { label linuxAgent }
    options { skipDefaultCheckout(true) }
    stages {       
        stage('verbose test') {
            agent { label zOsAgentLabel }
            steps {
                script {
                    // Verbose
                    verbose = env.VERBOSE && env.VERBOSE == 'true' ? true : false
                    buildVerbose = verbose ? '-v' : ''
                    if ( verbose ) {
                        echo sh(script: 'env|sort', returnStdout: true)
                    }
                }
            }
        }

        stage('execute') {
            steps {
                script{
                    node( zOsAgentLabel ) {
                        sh "$git -v")
                    }
                }
            }
        }
    }
}
